/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_enums_LSPS1PaymentState */

#ifndef _Included_org_ldk_enums_LSPS1PaymentState
#define _Included_org_ldk_enums_LSPS1PaymentState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_enums_LSPS1PaymentState
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_enums_LSPS1PaymentState_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
