/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_enums_LSPS1OrderState */

#ifndef _Included_org_ldk_enums_LSPS1OrderState
#define _Included_org_ldk_enums_LSPS1OrderState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_enums_LSPS1OrderState
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_enums_LSPS1OrderState_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
