/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKLSPS2ServiceEvent */

#ifndef _Included_org_ldk_impl_bindings_LDKLSPS2ServiceEvent
#define _Included_org_ldk_impl_bindings_LDKLSPS2ServiceEvent
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKLSPS2ServiceEvent
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKLSPS2ServiceEvent_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
