/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ldk_impl_bindings_LDKLSPS0Request */

#ifndef _Included_org_ldk_impl_bindings_LDKLSPS0Request
#define _Included_org_ldk_impl_bindings_LDKLSPS0Request
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ldk_impl_bindings_LDKLSPS0Request
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_ldk_impl_bindings_00024LDKLSPS0Request_init
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
